### ISSUE TITLE
Audit-traceability feature in the database. Register of all the action executed against the API (express global interceptor)

### ISSUE THREAD

**Issue by alexfradiani** [rootstrap/node-ts-api-base#108]

**Comment by Alxzu** [comment]
@zk182 @pablanco is this related with [this middleware](https://github.com/rootstrap/node-ts-api-base/blob/master/src/middlewares/error.middleware.ts)? In that case this issue could be close, right?

**Comment by Alxzu** [comment]
Nevermind, I just saw it says "traceability actions executed against the API" 🤦

**Comment by Alxzu** [comment]
Not needed for current scope
