### ISSUE TITLE
Change istanbul to NYC

### ISSUE THREAD

**Issue by nsantos16** [rootstrap/node-ts-api-base#164]
<img width="1270" alt="Screen Shot 2020-11-23 at 18 37 29" src="https://user-images.githubusercontent.com/9642510/100018262-f4d99800-2dba-11eb-99cd-131b2580991d.png">

**Comment by Alxzu** [comment]
@nsantos16 can you let us know if this is deprecated?

**Comment by nsantos16** [comment]
@Alxzu  According to the author of the library, yes.
For more information you can check the [README](https://github.com/gotwarlost/istanbul), but currently in this project we don't longer use this package, so I'll close this issue. Thanks for the double-check!
